fix inference mode crash in eval script.
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
[ERROR] Command failed with code 1: "/opt/isaaclab-venv/bin/python -m gaitnet_sim.scripts.eval_sweep --bundle data/bundles/bc6ad351ab3046ada4550ffd7839c6d7.pt --task GaitNet-Holes --mlflow_run= --terrain_length 2.0 presets=gpu_mpc"